### ISSUE TITLE
Request: convert to Kotlin Multiplatform

### ISSUE THREAD

**Issue by aSemy** [alllex/parsus#2]
Hi,

I'd like to use Parsus in a Kotlin/Native application (Windows/Linux/macOS). Since Parsus has 0 dependencies, I think this could be achieved with a minor code refactor, and updating the Gradle build config.

I've had a look at the codebase and from what I can see the only JVM specific dependencies are:

* `Matcher` in `RegexToken`
   https://github.com/alllex/parsus/blob/7185f7aec0871fe6241602997aebae064e151358/src/main/kotlin/me/alllex/parsus/token/RegexToken.kt#L5
* The `RegexOption` flags ([`RegexOptions` itself is multiplatform](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-regex-option/), but the `COMMENTS` and `LITERAL` options are JVM-only)
   https://github.com/alllex/parsus/blob/7185f7aec0871fe6241602997aebae064e151358/src/main/kotlin/me/alllex/parsus/token/RegexToken.kt#L24-L26
* AssertK is already multiplatform, so no changes are needed (except for changing the dependency)
    https://github.com/alllex/parsus/blob/7185f7aec0871fe6241602997aebae064e151358/build.gradle.kts#L19
* Replace `org.junit.Test` with [`kotlin.test.Test`](https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/-test/)
    https://github.com/alllex/parsus/blob/7185f7aec0871fe6241602997aebae064e151358/src/test/kotlin/me/alllex/parsus/Tests.kt#L13

I'm willing to make a PR, so if you're interested I can submit one and see what it looks like in practice.

**Comment by alllex** [comment]
Hey! Thank you for your interest!
I wanted to make Parsus multiplatform for a while, but never found the time. So please, go ahead with the PR!

After some recent refactoring, I've already changed testing annotations to `kotlin.test.Test`.
With regards to regex tokens, I think we can make the whole `RegexToken` an expected class and provide the implementations for each platform separately.
