### ISSUE TITLE
Optional token?

### ISSUE THREAD

**Issue by aSemy** [alllex/parsus#7]
I'm trying to write a parser for a SemVer string that might or might not end in `-SNAPSHOT`.

How can I tell Parsus that the token is optional?

Currently I get an exception, because the SNAPSHOT token parser is mandatory.

```kotlin
import me.alllex.parsus.parser.*
import me.alllex.parsus.token.literalToken
import me.alllex.parsus.token.regexToken

fun main() {
  println(SemVerParser.parseEntireOrThrow("1.2.3-SNAPSHOT")) // Success ✅
  // prints: 1.2.3-SNAPSHOT
  println(SemVerParser.parseEntireOrThrow("1.2.3")) // ERROR ❌
  // Exception in thread "main" ParseException(MismatchedToken(expected=LiteralToken('-'), found=TokenMatch(token=Token(EOF), offset=5, length=1)))

}

private object SemVerParser : Grammar<SemVer>() {
  private val dotSeparator by literalToken(".")
  private val dashSeparator by literalToken("-")

  /** Non-negative number that is either 0, or does not start with 0 */
  private val number: Parser<Int> by regexToken("""0|[1-9]\d*""").map { it.text.toInt() }

  private val snapshot: Parser<Boolean> by -dashSeparator * literalToken("""SNAPSHOT""")
    .map { it.text == "SNAPSHOT" }

  override val root: Parser<SemVer> by parser {
    val major = number()
    dotSeparator()
    val minor = number()
    dotSeparator()
    val patch = number()
    val snapshot = snapshot() // how can I make this optional?
    SemVer(
      major = major,
      minor = minor,
      patch = patch,
      snapshot = snapshot,
    )
  }
}

private data class SemVer(
  val major: Int,
  val minor: Int,
  val patch: Int,
  val snapshot: Boolean,
) {
  override fun toString(): String =
    "$major.$minor.$patch" + if (snapshot) "-SNAPSHOT" else ""
}
```

**Comment by alllex** [comment]
You can either directly use `poll` / `tryOrNull` functions in the `root` parser:
```
val snapshot = tryOrNull(snapshot) ?: false
```

**Comment by aSemy** [comment]
I found it out, there's an [`optional()`](https://github.com/alllex/parsus/blob/f0afbd3e9c89da15a6802c5a71cefeadeefb956f/src/commonMain/kotlin/me/alllex/parsus/parser/combinators.kt#L50-L52) function.


```
private object SemVerParser : Grammar<SemVer>() {
  private val dotSeparator by literalToken(".")
  private val dashSeparator by literalToken("-")

  /** Non-negative number that is either 0, or does not start with 0 */
  private val number: Parser<Int> by regexToken("""0|[1-9]\d*""").map { it.text.toInt() }

  private val metadata by optional(-dashSeparator * regexToken(""".+"""))
    .map { it?.text ?: "" }

  override val root: Parser<SemVer> by parser {
    val major = number()
    dotSeparator()
    val minor = number()
    dotSeparator()
    val patch = number()
    val metadata = metadata()
    SemVer(
      major = major,
      minor = minor,
      patch = patch,
      snapshot = metadata == "SNAPSHOT",
    )
  }
}
```

An example in the README would be appreciated 🙏

**Comment by alllex** [comment]
There are many ways you can go about this.

The most concise is to use the `unaryPlus` on the parser:
```kotlin
val snapshot = +snapshot // returns Boolean
```

This is a shorthand for the `checkPresent(snapshot)` [function](https://javadoc.io/static/me.alllex.parsus/parsus-jvm/0.4.0/parsus/me.alllex.parsus.parser/check-present.html?query=suspend%20fun%20ParsingScope.checkPresent(p:%20Parser%3CAny%3E):%20Boolean).

You could also use the nullable combinators for optional tokens: `poll` / `tryOrNull`
```kotlin
val snapshot = tryOrNull(snapshot) ?: false
```

And there is also [`optional`](https://javadoc.io/static/me.alllex.parsus/parsus-jvm/0.4.0/parsus/me.alllex.parsus.parser/optional.html?query=fun%20%3CT%20:%20Any%3E%20optional(parser:%20Parser%3CT%3E):%20Parser%3CT?%3E) combinator that you could you when defining the `snapshot` parser itself.

**Comment by alllex** [comment]
Oh, great, you found it already!

I will try to improve the readme in this regard. Thanks for the idea!

Note that the grammar in your last comment would also parse strings like `1.2.3-BLAH`. It may depend whether this is something you want to support.
