### ISSUE TITLE
Case insensitive matching

### ISSUE THREAD

**Issue by aSemy** [alllex/parsus#9]
I'm trying to write a parser for the Factorio changelog format, which is very particular and easy to get wrong. For example, the date field is optional, and must be captialized as `Date`. However, it's easy to make a mistake and use the wrong capitalization, e.g. `date` or `DATE`. 

I'd like to be able to use Parsus to capture the values leniently, so that I can later do validation.

#### Literal tokens

Adding an `ignoreCase` parameter to [`LiteralToken`](https://github.com/alllex/parsus/blob/v0.4.0/src/commonMain/kotlin/me/alllex/parsus/token/LiteralToken.kt) would be helpful, and easy to implement.

```kotlin
class LiteralToken(
  private val string: String,
  private val ignoreCase: Boolean = false,
  name: String? = null,
  ignored: Boolean = false
) : Token(name, ignored) {

  override fun match(input: CharSequence, fromIndex: Int): Int =
    when {
      input.startsWith(string, fromIndex, ignoreCase = ignoreCase) -> string.length
      else                                                         -> 0
    }
}
```

#### Regex token

Kotlin's Regex has an option to ignore the case
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-regex-option/-i-g-n-o-r-e_-c-a-s-e.html

What do you think about adding a parameter to set the regex options in the `regexToken()` function? For example:

```kotlin
private val datePrefix by regexToken("""date:\s*""", options = setOf(RegexOption.IGNORE_CASE))
```

Although perhaps implementing a custom builder might be more succinct:

```kotlin
private val datePrefix by regexToken("""date:\s*""") {
 options += RegexOption.IGNORE_CASE
}
```

Or maybe just a boolean flag, for simplicity

```kotlin
private val datePrefix by regexToken("""date:\s*""", ignoreCase = true)
```

**Comment by alllex** [comment]
It makes sense to extend the functionality of string literals. I created a PR for it:
- #13 

As for regexes, you can already do that, because there is an overload that takes a constructed `Regex` as a value:
```kotlin
val datePrefix by regexToken("""\s*""".toRegex(RegexOption.IGNORE_CASE))
```

If that's something you want to write often, you can always create another overload for `regexToken` function that takes options, or directly something like `regexTokenIgnoreCase(...)`
